# Generated by Django 6.1 on 2026-08-07 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CauseOfDeath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cause_name", models.CharField(max_length=255, unique=True)),
                ("cause_category", models.CharField(blank=True, max_length=120)),
                ("cause_code", models.CharField(blank=True, max_length=32)),
            ],
            options={
                "db_table": "cause_of_death",
                "ordering": ["cause_name"],
            },
        ),
        migrations.CreateModel(
            name="MortalityRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("location", models.CharField(default="Malaysia", max_length=120)),
                (
                    "age_band",
                    models.CharField(
                        choices=[
                            ("0-14", "0-14"),
                            ("15-40", "15-40"),
                            ("41-59", "41-59"),
                            ("60+", "60 and over"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("both", "Both"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "certification",
                    models.CharField(
                        choices=[
                            ("medical", "Medically certified"),
                            ("non_medical", "Non-medically certified"),
                        ],
                        default="medical",
                        max_length=16,
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField()),
                ("death_count", models.PositiveIntegerField()),
                ("share_pct", models.FloatField()),
                ("group_total", models.PositiveIntegerField()),
                (
                    "cause",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mortality_records",
                        to="core.causeofdeath",
                    ),
                ),
            ],
            options={
                "db_table": "mortality_record",
                "ordering": ["age_band", "sex", "rank"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "year",
                            "location",
                            "age_band",
                            "sex",
                            "certification",
                            "cause",
                        ),
                        name="unique_mortality_row",
                    )
                ],
            },
        ),
    ]
